import random
from categories import CATEGORIES


def shuffle_array(arr):
    shuffled = arr.copy()
    random.shuffle(shuffled)
    return shuffled


TYPE_POOL = [
    "Normal",
    "Fire",
    "Water",
    "Electric",
    "Grass",
    "Ice",
    "Fighting",
    "Poison",
    "Ground",
    "Flying",
    "Psychic",
    "Bug",
    "Rock",
    "Ghost",
    "Dragon",
    "Dark",
    "Steel",
    "Fairy",
    "Normal/Flying",
    "Fire/Flying",
    "Water/Flying",
    "Grass/Poison",
    "Fire/Ground",
    "Bug/Poison",
    "Ground/Flying",
    "Grass/Flying",
    "Ice/Flying",
    "Psychic/Flying",
    "Bug/Flying",
    "Poison/Flying",
    "Fire/Fighting",
    "Grass/Fighting",
    "Electric/Steel",
    "Water/Psychic",
    "Grass/Psychic",
    "Fire/Psychic",
    "Normal/Psychic",
    "Rock/Water",
    "Bug/Grass",
    "Rock/Ground",
    "Water/Ground",
    "Rock/Fighting",
    "Water/Fighting",
    "Bug/Fire",
    "Bug/Rock",
    "Bug/Steel",
    "Poison/Ground",
    "Poison/Bug",
    "Ground/Rock",
    "Ground/Steel",
    "Rock/Steel",
    "Normal/Rock",
    "Fire/Rock",
    "Bug/Ground",
    "Water/Ground",
    "Electric/Dragon",
    "Psychic/Dragon",
    "Dragon/Flying",
    "Psychic/Fairy",
    "Steel/Fairy",
    "Ghost/Poison",
    "Ghost/Fire",
    "Ghost/Grass",
    "Dark/Psychic",
    "Dark/Ghost",
    "Dark/Fighting",
    "Steel/Electric",
    "Steel/Ice",
    "Steel/Fire",
    "Steel/Rock",
    "Normal/Ice",
    "Water/Ice",
    "Ice/Psychic",
    "Ice/Ghost",
    "Ice/Dragon",
    "Ice/Steel",
    "Grass/Ice",
    "Grass/Steel",
    "Grass/Dragon",
    "Grass/Fire",
    "Ground/Steel",
    "Ground/Poison",
    "Ground/Fighting",
    "Flying/Normal",
    "Flying/Poison",
    "Flying/Fighting",
    "Flying/Bug",
    "Flying/Fairy",
]

NUMBER_POOL = [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "25",
    "30",
    "35",
    "40",
    "45",
    "50",
    "60",
    "65",
    "70",
    "75",
    "80",
    "85",
    "90",
    "95",
    "100",
    "105",
    "110",
    "115",
    "120",
    "125",
    "130",
    "135",
    "140",
    "145",
    "150",
    "151",
    "152",
    "155",
    "160",
    "165",
    "170",
    "175",
    "180",
    "185",
    "190",
    "195",
    "200",
    "250",
    "300",
    "350",
    "400",
    "450",
    "500",
    "10%",
    "50%",
    "100%",
    "60 minutes",
    "120 minutes",
]

REGION_POOL = [
    "Kanto",
    "Johto",
    "Hoenn",
    "Sinnoh",
    "Unova",
    "Kalos",
    "Alola",
    "Galar",
    "Paldea",
    "Indigo Plateau",
    "New Bark Town",
    "Pallet Town",
    "Cerulean City",
    "Lavender Town",
]

PROFESSOR_POOL = [
    "Professor Oak",
    "Professor Elm",
    "Professor Birch",
    "Professor Rowan",
    "Professor Juniper",
    "Professor Sycamore",
    "Professor Kukui",
    "Professor Magnolia",
    "Professor Sada",
    "Professor Turo",
    "Professor Burnet",
    "Professor Cole",
    "Professor Karan",
    "Professor Pino",
    "Professor Laven",
]

ITEM_POOL = [
    "Fire Stone",
    "Water Stone",
    "Thunder Stone",
    "Leaf Stone",
    "Moon Stone",
    "Sun Stone",
    "Shiny Stone",
    "Dusk Stone",
    "Dawn Stone",
    "Oval Stone",
    "King's Rock",
    "Metal Coat",
    "Dragon Scale",
    "Upgrade",
    "Dubious Disc",
    "Protector",
    "Link Cable",
    "Deep Sea Tooth",
    "Prism Scale",
    "Razor Claw",
    "Razor Fang",
    "Electirizer",
    "Magmarizer",
    "Damascus Steel",
    "Soothe Bell",
    "Everstone",
    "Choice Band",
    "Life Orb",
    "Leftovers",
    "Focus Sash",
]

COLOR_POOL = [
    "Red",
    "Blue",
    "Green",
    "Yellow",
    "Orange",
    "Purple",
    "Pink",
    "White",
    "Black",
    "Brown",
    "Gray",
    "Grey",
    "Gold",
    "Silver",
    "Light Blue",
    "Dark Blue",
    "Light Green",
    "Dark Green",
]

TRAIT_POOL = [
    "Blue with orange fins",
    "Red and white",
    "Yellow and black",
    "Blue and yellow",
    "Black and white",
    "Multi-colored",
    "Spotted",
    "Striped",
    "Golden",
    "Silver",
]


def categorize_answer(answer):
    if answer in POKEMON_NAMES_POOL:
        return "pokemon"
    if answer in TYPE_POOL or "/" in answer:
        return "type"
    if answer.replace("%", "").replace(" ", "").isdigit() or answer in NUMBER_POOL:
        return "number"
    if any(region.lower() in answer.lower() for region in REGION_POOL):
        return "region"
    if answer.startswith("Professor") or answer in ["Satoshi", "Ash"]:
        return "professor"
    if answer in COLOR_POOL:
        return "color"
    if any(
        item in answer for item in ["Stone", "Ball", "Orb", "Coat", "Scale", "Bell"]
    ):
        return "item"
    if "with" in answer.lower() or "and" in answer or "or" in answer:
        return "trait"
    if len(answer.split()) > 2:
        return "phrase"
    return "pokemon"


def get_wrong_options_pool(correct, category):
    pools = {
        "pokemon": POKEMON_NAMES_POOL,
        "type": TYPE_POOL,
        "number": NUMBER_POOL,
        "region": REGION_POOL,
        "professor": PROFESSOR_POOL,
        "color": COLOR_POOL,
        "item": ITEM_POOL,
        "trait": TRAIT_POOL,
    }
    pool = pools.get(category, POKEMON_NAMES_POOL)
    return [p for p in pool if p != correct]


def generate_options(correct, all_pokemon):
    category = categorize_answer(correct)
    wrong_pool = get_wrong_options_pool(correct, category)

    if len(wrong_pool) < 3:
        wrong_pool = [p for p in POKEMON_NAMES_POOL if p != correct]

    options = [correct]
    shuffled_others = shuffle_array(wrong_pool)[:3]
    options.extend(shuffled_others)
    shuffled_options = shuffle_array(options)
    labels = ["A", "B", "C", "D"]
    return [(labels[i], opt) for i, opt in enumerate(shuffled_options)]


ALL_POKEMON = [
    "Bulbasaur",
    "Ivysaur",
    "Venusaur",
    "Charmander",
    "Charmeleon",
    "Charizard",
    "Squirtle",
    "Wartortle",
    "Blastoise",
    "Caterpie",
    "Metapod",
    "Butterfree",
    "Weedle",
    "Kakuna",
    "Beedrill",
    "Pidgey",
    "Pidgeotto",
    "Pidgeot",
    "Rattata",
    "Raticate",
    "Spearow",
    "Fearow",
    "Ekans",
    "Arbok",
    "Pikachu",
    "Raichu",
    "Sandshrew",
    "Sandslash",
    "Nidorina",
    "Nidoqueen",
    "Nidorino",
    "Nidoking",
    "Clefairy",
    "Clefable",
    "Vulpix",
    "Ninetales",
    "Jigglypuff",
    "Wigglytuff",
    "Zubat",
    "Golbat",
    "Oddish",
    "Gloom",
    "Vileplume",
    "Paras",
    "Parasect",
    "Venonat",
    "Venomoth",
    "Diglett",
    "Dugtrio",
    "Meowth",
    "Persian",
    "Psyduck",
    "Golduck",
    "Mankey",
    "Primeape",
    "Growlithe",
    "Arcanine",
    "Poliwag",
    "Poliwhirl",
    "Poliwrath",
    "Abra",
    "Kadabra",
    "Alakazam",
    "Machop",
    "Machoke",
    "Machamp",
    "Bellsprout",
    "Weepinbell",
    "Victreebel",
    "Tentacool",
    "Tentacruel",
    "Geodude",
    "Graveler",
    "Golem",
    "Ponyta",
    "Rapidash",
    "Slowpoke",
    "Slowbro",
    "Magnemite",
    "Magneton",
    "Farfetch'd",
    "Doduo",
    "Dodrio",
    "Seel",
    "Dewgong",
    "Grimer",
    "Muk",
    "Shellder",
    "Cloyster",
    "Gastly",
    "Haunter",
    "Gengar",
    "Onix",
    "Drowzee",
    "Hypno",
    "Krabby",
    "Kingler",
    "Voltorb",
    "Electrode",
    "Exeggcute",
    "Exeggutor",
    "Cubone",
    "Marowak",
    "Hitmonlee",
    "Hitmonchan",
    "Lickitung",
    "Koffing",
    "Weezing",
    "Rhyhorn",
    "Rhydon",
    "Chansey",
    "Tangela",
    "Kangaskhan",
    "Horsea",
    "Seadra",
    "Goldeen",
    "Seaking",
    "Staryu",
    "Starmie",
    "Mr. Mime",
    "Scyther",
    "Jynx",
    "Electabuzz",
    "Magmar",
    "Pinsir",
    "Tauros",
    "Magikarp",
    "Gyarados",
    "Lapras",
    "Ditto",
    "Eevee",
    "Vaporeon",
    "Jolteon",
    "Flareon",
    "Porygon",
    "Omanyte",
    "Omastar",
    "Kabuto",
    "Kabutops",
    "Aerodactyl",
    "Snorlax",
    "Articuno",
    "Zapdos",
    "Moltres",
    "Dratini",
    "Dragonair",
    "Dragonite",
    "Mewtwo",
    "Mew",
    "Chikorita",
    "Bayleef",
    "Meganium",
    "Cyndaquil",
    "Quilava",
    "Typhlosion",
    "Totodile",
    "Croconaw",
    "Feraligatr",
    "Sentret",
    "Furret",
    "Hoothoot",
    "Noctowl",
    "Ledyba",
    "Ledian",
    "Spinarak",
    "Ariados",
    "Crobat",
    "Chinchou",
    "Lanturn",
    "Pichu",
    "Cleffa",
    "Igglybuff",
    "Togepi",
    "Togetic",
    "Natu",
    "Xatu",
    "Mareep",
    "Flaaffy",
    "Ampharos",
    "Bellossom",
    "Marill",
    "Azumarill",
    "Sudowoodo",
    "Politoed",
    "Hoppip",
    "Skiploom",
    "Jumpluff",
    "Aipom",
    "Sunkern",
    "Sunflora",
    "Yanma",
    "Wooper",
    "Quagsire",
    "Espeon",
    "Umbreon",
    "Murkrow",
    "Slowking",
    "Misdreavus",
    "Unown",
    "Wobbuffet",
    "Girafarig",
    "Pineco",
    "Forretress",
    "Dunsparce",
    "Gligar",
    "Steelix",
    "Snubbull",
    "Granbull",
    "Qwilfish",
    "Scizor",
    "Shuckle",
    "Heracross",
    "Sneasel",
    "Teddiursa",
    "Ursaring",
    "Slugma",
    "Magcargo",
    "Swinub",
    "Piloswine",
    "Corsola",
    "Remoraid",
    "Octillery",
    "Delibird",
    "Mantine",
    "Skarmory",
    "Houndour",
    "Houndoom",
    "Kingdra",
    "Phanpy",
    "Donphan",
    "Porygon2",
    "Stantler",
    "Smeargle",
    "Tyrogue",
    "Hitmontop",
    "Smoochum",
    "Elekid",
    "Magby",
    "Miltank",
    "Blissey",
    "Raikou",
    "Entei",
    "Suicune",
    "Larvitar",
    "Pupitar",
    "Tyranitar",
    "Lugia",
    "Ho-Oh",
    "Celebi",
    "Treecko",
    "Grovyle",
    "Sceptile",
    "Torchic",
    "Combusken",
    "Blaziken",
    "Mudkip",
    "Marshtomp",
    "Swampert",
    "Poochyena",
    "Mightyena",
    "Zigzagoon",
    "Linoone",
    "Wurmple",
    "Silcoon",
    "Beautifly",
    "Cascoon",
    "Dustox",
    "Lotad",
    "Lombre",
    "Ludicolo",
    "Seedot",
    "Nuzleaf",
    "Shiftry",
    "Taillow",
    "Swellow",
    "Wingull",
    "Pelipper",
    "Ralts",
    "Kirlia",
    "Gardevoir",
    "Surskit",
    "Masquerain",
    "Shroomish",
    "Breloom",
    "Slakoth",
    "Vigoroth",
    "Slaking",
    "Nincada",
    "Ninjask",
    "Shedinja",
    "Whismur",
    "Loudred",
    "Exploud",
    "Makuhita",
    "Hariyama",
    "Azurill",
    "Nosepass",
    "Skitty",
    "Delcatty",
    "Sableye",
    "Mawile",
    "Aron",
    "Lairon",
    "Aggron",
    "Meditite",
    "Medicham",
    "Electrike",
    "Manectric",
    "Plusle",
    "Minun",
    "Volbeat",
    "Illumise",
    "Roselia",
    "Gulpin",
    "Swalot",
    "Carvanha",
    "Sharpedo",
    "Wailmer",
    "Wailord",
    "Numel",
    "Camerupt",
    "Torkoal",
    "Spoink",
    "Grumpig",
    "Spinda",
    "Trapinch",
    "Vibrava",
    "Flygon",
    "Cacnea",
    "Cacturne",
    "Swablu",
    "Altaria",
    "Zangoose",
    "Seviper",
    "Lunatone",
    "Solrock",
    "Barboach",
    "Whiscash",
    "Corphish",
    "Crawdaunt",
    "Baltoy",
    "Claydol",
    "Lileep",
    "Cradily",
    "Anorith",
    "Armaldo",
    "Feebas",
    "Milotic",
    "Castform",
    "Kecleon",
    "Shuppet",
    "Banette",
    "Duskull",
    "Dusclops",
    "Tropius",
    "Chimecho",
    "Absol",
    "Wynaut",
    "Snorunt",
    "Glalie",
    "Spheal",
    "Sealeo",
    "Walrein",
    "Clamperl",
    "Huntail",
    "Gorebyss",
    "Relicanth",
    "Luvdisc",
    "Bagon",
    "Shelgon",
    "Salamence",
    "Beldum",
    "Metang",
    "Metagross",
    "Regirock",
    "Regice",
    "Registeel",
    "Latias",
    "Latios",
    "Kyogre",
    "Groudon",
    "Rayquaza",
    "Jirachi",
    "Deoxys",
    "Turtwig",
    "Grotle",
    "Torterra",
    "Chimchar",
    "Monferno",
    "Infernape",
    "Piplup",
    "Prinplup",
    "Empoleon",
    "Starly",
    "Staravia",
    "Staraptor",
    "Bidoof",
    "Bibarel",
    "Kricketot",
    "Kricketune",
    "Shinx",
    "Luxio",
    "Luxray",
    "Budew",
    "Roserade",
    "Cranidos",
    "Rampardos",
    "Shieldon",
    "Bastiodon",
    "Burmy",
    "Wormadam",
    "Mothim",
    "Combee",
    "Vespiquen",
    "Pachirisu",
    "Buizel",
    "Floatzel",
    "Cherubi",
    "Cherrim",
    "Shellos",
    "Gastrodon",
    "Ambipom",
    "Drifloon",
    "Drifblim",
    "Buneary",
    "Lopunny",
    "Mismagius",
    "Honchkrow",
    "Glameow",
    "Purugly",
    "Chingling",
    "Stunky",
    "Skuntank",
    "Bronzor",
    "Bronzong",
    "Bonsly",
    "Mime Jr.",
    "Happiny",
    "Chatot",
    "Spiritomb",
    "Gible",
    "Gabite",
    "Garchomp",
    "Munchlax",
    "Riolu",
    "Lucario",
    "Hippopotas",
    "Hippowdon",
    "Skorupi",
    "Drapion",
    "Croagunk",
    "Toxicroak",
    "Carnivine",
    "Finneon",
    "Lumineon",
    "Mantyke",
    "Snover",
    "Abomasnow",
    "Weavile",
    "Magnezone",
    "Lickilicky",
    "Rhyperior",
    "Tangrowth",
    "Electivire",
    "Magmortar",
    "Togekiss",
    "Yanmega",
    "Leafeon",
    "Glaceon",
    "Gliscor",
    "Mamoswine",
    "Porygon-Z",
    "Gallade",
    "Probopass",
    "Dusknoir",
    "Froslass",
    "Rotom",
    "Uxie",
    "Mesprit",
    "Azelf",
    "Dialga",
    "Palkia",
    "Heatran",
    "Regigigas",
    "Giratina",
    "Cresselia",
    "Phione",
    "Manaphy",
    "Darkrai",
    "Shaymin",
    "Arceus",
    "Victini",
    "Snivy",
    "Servine",
    "Serperior",
    "Tepig",
    "Pignite",
    "Emboar",
    "Oshawott",
    "Dewott",
    "Samurott",
    "Patrat",
    "Watchog",
    "Lillipup",
    "Herdier",
    "Stoutland",
    "Purrloin",
    "Liepard",
    "Pansage",
    "Simisage",
    "Pansear",
    "Simisear",
    "Panpour",
    "Simipour",
    "Munna",
    "Musharna",
    "Pidove",
    "Tranquill",
    "Unfezant",
    "Blitzle",
    "Zebstrika",
    "Roggenrola",
    "Boldore",
    "Gigalith",
    "Woobat",
    "Swoobat",
    "Drilbur",
    "Excadrill",
    "Audino",
    "Timburr",
    "Gurdurr",
    "Conkeldurr",
    "Tympole",
    "Palpitoad",
    "Seismitoad",
    "Throh",
    "Sawk",
    "Sewaddle",
    "Swadloon",
    "Leavanny",
    "Venipede",
    "Whirlipede",
    "Scolipede",
    "Cottonee",
    "Whimsicott",
    "Petilil",
    "Lilligant",
    "Basculin",
    "Sandile",
    "Krokorok",
    "Krookodile",
    "Darumaka",
    "Darmanitan",
    "Maractus",
    "Dwebble",
    "Crustle",
    "Scraggy",
    "Scrafty",
    "Sigilyph",
    "Yamask",
    "Cofagrigus",
    "Tirtouga",
    "Carracosta",
    "Archen",
    "Archeops",
    "Trubbish",
    "Garbodor",
    "Zorua",
    "Zoroark",
    "Minccino",
    "Cinccino",
    "Gothita",
    "Gothorita",
    "Gothitelle",
    "Solosis",
    "Duosion",
    "Reuniclus",
    "Ducklett",
    "Swanna",
    "Vanillite",
    "Vanillish",
    "Vanilluxe",
    "Deerling",
    "Sawsbuck",
    "Emolga",
    "Karrablast",
    "Escavalier",
    "Foongus",
    "Amoonguss",
    "Frillish",
    "Jellicent",
    "Alomomola",
    "Joltik",
    "Galvantula",
    "Ferroseed",
    "Ferrothorn",
    "Klink",
    "Klang",
    "Klinklang",
    "Tynamo",
    "Eelektrik",
    "Eelektross",
    "Elgyem",
    "Beheeyem",
    "Lampent",
    "Chandelure",
    "Axew",
    "Fraxure",
    "Haxorus",
    "Cubchoo",
    "Beartic",
    "Cryogonal",
    "Shelmet",
    "Accelgor",
    "Stunfisk",
    "Mienfoo",
    "Mienshao",
    "Druddigon",
    "Golett",
    "Golurk",
    "Pawniard",
    "Bisharp",
    "Bouffalant",
    "Rufflet",
    "Braviary",
    "Vullaby",
    "Mandibuzz",
    "Heatmor",
    "Durant",
    "Deino",
    "Zweilous",
    "Hydreigon",
    "Larvesta",
    "Volcarona",
    "Cobalion",
    "Terrakion",
    "Virizion",
    "Tornadus",
    "Thundurus",
    "Reshiram",
    "Zekrom",
    "Landorus",
    "Kyurem",
    "Keldeo",
    "Meloetta",
    "Genesect",
    "Chespin",
    "Quilladin",
    "Chesnaught",
    "Fennekin",
    "Braixen",
    "Delphox",
    "Froakie",
    "Frogadier",
    "Greninja",
    "Bunnelby",
    "Diggersby",
    "Fletchling",
    "Fletchinder",
    "Talonflame",
    "Scatterbug",
    "Spewpa",
    "Vivillon",
    "Litleo",
    "Pyroar",
    "Flabebe",
    "Floette",
    "Florges",
    "Skiddo",
    "Gogoat",
    "Pancham",
    "Pangoro",
    "Furfrou",
    "Espurr",
    "Meowstic",
    "Honedge",
    "Doublade",
    "Aegislash",
    "Spritzee",
    "Aromatisse",
    "Swirlix",
    "Slurpuff",
    "Inkay",
    "Malamar",
    "Binacle",
    "Barbaracle",
    "Skrelp",
    "Dragalge",
    "Clauncher",
    "Clawitzer",
    "Helioptile",
    "Heliolisk",
    "Tyrunt",
    "Tyrantrum",
    "Amaura",
    "Aurorus",
    "Sylveon",
    "Hawlucha",
    "Dedenne",
    "Carbink",
    "Goomy",
    "Sliggoo",
    "Goodra",
    "Klefki",
    "Phantump",
    "Trevenant",
    "Pumpkaboo",
    "Gourgeist",
    "Bergmite",
    "Avalugg",
    "Noibat",
    "Noivern",
    "Xerneas",
    "Yveltal",
    "Zygarde",
    "Diancie",
    "Hoopa",
    "Volcanion",
    "Rowlet",
    "Dartrix",
    "Decidueye",
    "Litten",
    "Torracat",
    "Incineroar",
    "Popplio",
    "Brionne",
    "Primarina",
    "Pikipek",
    "Trumbeak",
    "Toucannon",
    "Yungoos",
    "Gumshoos",
    "Grubbin",
    "Charjabug",
    "Vikavolt",
    "Crabrawler",
    "Crabominable",
    "Plumeria",
    "Cutiefly",
    "Ribombee",
    "Rockruff",
    "Lycanroc",
    "Wishiwashi",
    "Mareanie",
    "Toxapex",
    "Mudbray",
    "Mudsdale",
    "Dewpider",
    "Araquanid",
    "Fomantis",
    "Lurantis",
    "Morelull",
    "Shiinotic",
    "Salandit",
    "Salazzle",
    "Stufful",
    "Bewear",
    "Bounsweet",
    "Steenee",
    "Tsareena",
    "Comfey",
    "Oranguru",
    "Passimian",
    "Wimpod",
    "Golisopod",
    "Sandygast",
    "Palossand",
    "Pyukumuku",
    "Type Null",
    "Silvally",
    "Minior",
    "Komala",
    "Turtonator",
    "Togedemaru",
    "Mimikyu",
    "Bruxish",
    "Drampa",
    "Dhelmise",
    "Jangmo-o",
    "Hakamo-o",
    "Tapu Koko",
    "Tapu Lele",
    "Tapu Bulu",
    "Tapu Fini",
    "Cosmog",
    "Cosmoem",
    "Solgaleo",
    "Lunala",
    "Nihilego",
    "Buzzwole",
    "Pheromosa",
    "Xurkitree",
    "Celesteela",
    "Kartana",
    "Guzzlord",
    "Necrozma",
    "Magearna",
    "Marshadow",
    "Poipole",
    "Naganadel",
    "Stakataka",
    "Blacephalon",
    "Zeraora",
    "Meltan",
    "Melmetal",
    "Grookey",
    "Thwackey",
    "Rillaboom",
    "Scorbunny",
    "Raboot",
    "Cinderace",
    "Sobble",
    "Drizzile",
    "Inteleon",
    "Skwovet",
    "Greedent",
    "Rookidee",
    "Corvisquire",
    "Corviknight",
    "Blipbug",
    "Dottler",
    "Orbeetle",
    "Nickit",
    "Thievul",
    "Gossifleur",
    "Eldegoss",
    "Wooloo",
    "Dubwool",
    "Chewtle",
    "Drednaw",
    "Yamper",
    "Boltund",
    "Rolycoly",
    "Carkol",
    "Coalossal",
    "Applin",
    "Flapple",
    "Appletun",
    "Silicobra",
    "Sandaconda",
    "Cramorant",
    "Arrokuda",
    "Barraskewda",
    "Toxel",
    "Toxtricity",
    "Sizzlipede",
    "Centiskorch",
    "Clobbopus",
    "Grapploct",
    "Sinistea",
    "Polteageist",
    "Hatenna",
    "Hattrem",
    "Hatterene",
    "Impidimp",
    "Morgrem",
    "Grimmsnarl",
    "Obstagoon",
    "Perrserker",
    "Cursola",
    "Sirfetch'd",
    "Mr. Rime",
    "Runerigus",
    "Milcery",
    "Alcremie",
    "Falinks",
    "Pincurchin",
    "Snom",
    "Frosmoth",
    "Stonjourner",
    "Eiscue",
    "Morpeko",
    "Hatenna",
    "Clobbopus",
    "Centiskorch",
]

POKEMON_NAMES_POOL = list(set(ALL_POKEMON))

QUESTIONS = {
    "general": [
        {
            "question": "What is the first Pokemon in the Pokedex?",
            "answer": "Bulbasaur",
            "correct_emoji": "🌱",
        },
        {
            "question": "What type is Pikachu?",
            "answer": "Electric",
            "correct_emoji": "⚡",
        },
        {
            "question": "Who is the mascot of the Pokemon franchise?",
            "answer": "Pikachu",
            "correct_emoji": "🐭",
        },
        {
            "question": "How many original Pokemon were there in Generation I?",
            "answer": "151",
            "correct_emoji": "1️⃣5️⃣1️⃣",
        },
        {
            "question": "What professor gives you your first Pokemon in Kanto?",
            "answer": "Professor Oak",
            "correct_emoji": "👴",
        },
        {
            "question": "What is Ash Ketchum's Japanese name?",
            "answer": "Satoshi",
            "correct_emoji": "🎬",
        },
        {
            "question": "What color is Squirtle?",
            "answer": "Blue",
            "correct_emoji": "💙",
        },
        {
            "question": "What does the word 'Pokemon' mean?",
            "answer": "Pocket Monster",
            "correct_emoji": "👾",
        },
        {
            "question": "What is Team Rocket's main goal?",
            "answer": "To steal rare Pokemon",
            "correct_emoji": "🚀",
        },
        {
            "question": "How many legs does Onix have?",
            "answer": "0",
            "correct_emoji": "🐍",
        },
    ],
    "gen1": [
        {
            "question": "What is the evolved form of Charmander?",
            "answer": "Charmeleon",
            "correct_emoji": "🔥",
        },
        {
            "question": "What Pokemon is known as the 'Ship Pokemon'?",
            "answer": "Lapras",
            "correct_emoji": "🚢",
        },
        {
            "question": "What Pokemon can learn any TM?",
            "answer": "Mew",
            "correct_emoji": "🧬",
        },
        {
            "question": "What is the final evolution of Magikarp?",
            "answer": "Gyarados",
            "correct_emoji": "🌊",
        },
        {
            "question": "How many Pokedex entries are there in Gen 1?",
            "answer": "151",
            "correct_emoji": "1️⃣5️⃣1️⃣",
        },
        {
            "question": "What type is Articuno?",
            "answer": "Ice/Flying",
            "correct_emoji": "❄️",
        },
        {
            "question": "What is the only Pokemon that can learn Transform in Gen 1?",
            "answer": "Mew",
            "correct_emoji": "🔮",
        },
        {
            "question": "Which Pokemon is NOT a Legendary in Gen 1?",
            "answer": "Snorlax",
            "correct_emoji": "😴",
        },
        {
            "question": "In which city do you battle the Elite Four in Gen 1?",
            "answer": "Indigo Plateau",
            "correct_emoji": "🏔️",
        },
        {
            "question": "What is Mewtwo's type?",
            "answer": "Psychic",
            "correct_emoji": "🔮",
        },
    ],
    "gen2": [
        {
            "question": "What region is Generation II based on?",
            "answer": "Johto",
            "correct_emoji": "🌸",
        },
        {
            "question": "What is the evolved form of Chikorita?",
            "answer": "Bayleef",
            "correct_emoji": "🌿",
        },
        {
            "question": "What new type was introduced in Generation II?",
            "answer": "Dark",
            "correct_emoji": "🌑",
        },
        {
            "question": "How many Pokemon were added in Generation II?",
            "answer": "100",
            "correct_emoji": "1️⃣0️⃣0️⃣",
        },
        {
            "question": "What is Togetic evolved into?",
            "answer": "Togekiss",
            "correct_emoji": "🕊️",
        },
        {
            "question": "Which Pokemon can learn the move 'Headbutt' naturally?",
            "answer": "Sudowoodo",
            "correct_emoji": "🌳",
        },
        {
            "question": "What is the Shiny version of Gyarados?",
            "answer": "Blue with orange fins",
            "correct_emoji": "✨",
        },
        {
            "question": "Who is the champion of the Johto region?",
            "answer": "Lance",
            "correct_emoji": "🐉",
        },
        {
            "question": "What item do you need to evolve Pichu?",
            "answer": "Soothe Bell",
            "correct_emoji": "🔔",
        },
        {
            "question": "What is the Kimono Girl's Pokemon?",
            "answer": "Espeon",
            "correct_emoji": "🔮",
        },
    ],
    "gen3": [
        {
            "question": "What region is Generation III based on?",
            "answer": "Hoenn",
            "correct_emoji": "🌴",
        },
        {
            "question": "What is the evolved form of Mudkip?",
            "answer": "Marshtomp",
            "correct_emoji": "💧",
        },
        {
            "question": "What new type was introduced in Generation III?",
            "answer": "Steel",
            "correct_emoji": "⚙️",
        },
        {
            "question": "How many Pokemon were added in Generation III?",
            "answer": "135",
            "correct_emoji": "1️⃣3️⃣5️⃣",
        },
        {
            "question": "What is Rayquaza's type?",
            "answer": "Dragon/Flying",
            "correct_emoji": "🐉",
        },
        {
            "question": "What is the starter Pokemon of Hoenn?",
            "answer": "Torchic",
            "correct_emoji": "🐤",
        },
        {
            "question": "Who is the champion of Hoenn?",
            "answer": "Steven",
            "correct_emoji": "💎",
        },
        {
            "question": "What is Deoxys based on?",
            "answer": "DNA",
            "correct_emoji": "🧪",
        },
        {
            "question": "What is Latias/Latios's type?",
            "answer": "Psychic/Dragon",
            "correct_emoji": "🔮",
        },
        {
            "question": "What is Jirachi's classification?",
            "answer": "Wish Pokemon",
            "correct_emoji": "⭐",
        },
    ],
    "types": [
        {
            "question": "What type is super effective against Fire?",
            "answer": "Water",
            "correct_emoji": "💧",
        },
        {
            "question": "What type is super effective against Ghost?",
            "answer": "Dark",
            "correct_emoji": "🌑",
        },
        {
            "question": "What type is weak to Ice?",
            "answer": "Dragon",
            "correct_emoji": "🐉",
        },
        {
            "question": "What dual type is Fire/Ghost?",
            "answer": "Chandelure",
            "correct_emoji": "🕯️",
        },
        {
            "question": "How many Pokemon types are there total?",
            "answer": "18",
            "correct_emoji": "1️⃣8️⃣",
        },
        {
            "question": "What type is immune to Normal?",
            "answer": "Ghost",
            "correct_emoji": "👻",
        },
        {
            "question": "What type is super effective against Steel?",
            "answer": "Fire",
            "correct_emoji": "🔥",
        },
        {
            "question": "What type combination has no weaknesses?",
            "answer": "Normal/Ghost",
            "correct_emoji": "👻",
        },
        {
            "question": "What is the only type super effective against Poison?",
            "answer": "Ground",
            "correct_emoji": "🌍",
        },
        {
            "question": "What type does Fairy resist?",
            "answer": "Dark",
            "correct_emoji": "🌑",
        },
    ],
    "moves": [
        {
            "question": "What move has the highest base power?",
            "answer": "Explosion",
            "correct_emoji": "💥",
        },
        {
            "question": "What move always goes first?",
            "answer": "Quick Attack",
            "correct_emoji": "⚡",
        },
        {
            "question": "What move boosts your Attack stat?",
            "answer": "Swords Dance",
            "correct_emoji": "⚔️",
        },
        {
            "question": "What move has 120 power and 70 accuracy?",
            "answer": "Hyper Beam",
            "correct_emoji": "🔴",
        },
        {
            "question": "What move is Pikachu's signature move?",
            "answer": "Volt Tackle",
            "correct_emoji": "⚡",
        },
        {
            "question": "What move causes fainting if it hits?",
            "answer": "Fissure",
            "correct_emoji": "🕳️",
        },
        {
            "question": "What move restores HP based on damage dealt?",
            "answer": "Drain Punch",
            "correct_emoji": "💪",
        },
        {
            "question": "What move is super effective against dragons?",
            "answer": "Ice Beam",
            "correct_emoji": "❄️",
        },
        {
            "question": "What move prevents the opponent from escaping?",
            "answer": "Block",
            "correct_emoji": "🚧",
        },
        {
            "question": "What is the signature move of Crescelia?",
            "answer": "Moonblast",
            "correct_emoji": "🌙",
        },
    ],
    "pokedex": [
        {
            "question": "What Pokemon is #001 in the National Pokedex?",
            "answer": "Bulbasaur",
            "correct_emoji": "🌱",
        },
        {
            "question": "What Pokemon is #150 in the National Pokedex?",
            "answer": "Mewtwo",
            "correct_emoji": "🔮",
        },
        {
            "question": "What Pokemon is #151 in the National Pokedex?",
            "answer": "Mew",
            "correct_emoji": "🧬",
        },
        {
            "question": "What Pokemon is #493 in the National Pokedex?",
            "answer": "Arceus",
            "correct_emoji": "⚡",
        },
        {
            "question": "What Pokemon is #649 in the National Pokedex?",
            "answer": "Genesect",
            "correct_emoji": "🤖",
        },
        {
            "question": "What Pokemon is #94 in the National Pokedex?",
            "answer": "Gengar",
            "correct_emoji": "👻",
        },
        {
            "question": "What Pokemon is #6 in the National Pokedex?",
            "answer": "Charizard",
            "correct_emoji": "🔥",
        },
        {
            "question": "What Pokemon is #131 in the National Pokedex?",
            "answer": "Lapras",
            "correct_emoji": "🚢",
        },
        {
            "question": "What Pokemon is #143 in the National Pokedex?",
            "answer": "Snorlax",
            "correct_emoji": "😴",
        },
        {
            "question": "What Pokemon is #25 in the National Pokedex?",
            "answer": "Pikachu",
            "correct_emoji": "⚡",
        },
    ],
    "legendary": [
        {
            "question": "What is the creation trio?",
            "answer": "Dialga, Palkia, Giratina",
            "correct_emoji": "⏰",
        },
        {
            "question": "What is considered the most powerful Legendary?",
            "answer": "Arceus",
            "correct_emoji": "⚡",
        },
        {
            "question": "What is the weather trio?",
            "answer": "Groudon, Kyogre, Rayquaza",
            "correct_emoji": "🌧️",
        },
        {
            "question": "What is Mewtwo's classification?",
            "answer": "Genetic Pokemon",
            "correct_emoji": "🧬",
        },
        {
            "question": "How many creation trio members are there?",
            "answer": "3",
            "correct_emoji": "3️⃣",
        },
        {
            "question": "What is the mascot of Pokemon Diamond?",
            "answer": "Palkia",
            "correct_emoji": "💎",
        },
        {
            "question": "What is Xerneas's type?",
            "answer": "Fairy",
            "correct_emoji": "✨",
        },
        {
            "question": "What is Zacian associated with?",
            "answer": "Sword",
            "correct_emoji": "⚔️",
        },
        {
            "question": "What is the lake trio?",
            "answer": "Uxie, Mesprit, Azelf",
            "correct_emoji": "🗺️",
        },
        {
            "question": "What changes forms based on plate held?",
            "answer": "Arceus",
            "correct_emoji": "⚡",
        },
    ],
    "evolution": [
        {
            "question": "What level does Charmeleon evolve?",
            "answer": "16",
            "correct_emoji": "🔢",
        },
        {
            "question": "What stone evolves Eevee into Flareon?",
            "answer": "Fire Stone",
            "correct_emoji": "🔥",
        },
        {
            "question": "What level does Magikarp evolve?",
            "answer": "20",
            "correct_emoji": "2️⃣0️⃣",
        },
        {
            "question": "What item evolves Haunter in trade?",
            "answer": "Link Cable",
            "correct_emoji": "🔗",
        },
        {
            "question": "What is Pichu's pre-evolution?",
            "answer": "Pikachu",
            "correct_emoji": "🐭",
        },
        {
            "question": "What evolves into Sylveon?",
            "answer": "Eevee",
            "correct_emoji": "🐰",
        },
        {
            "question": "What level does Larvitar evolve into Pupitar?",
            "answer": "30",
            "correct_emoji": "3️⃣0️⃣",
        },
        {
            "question": "What trade evolution requires an upgrade?",
            "answer": "Porygon",
            "correct_emoji": "💻",
        },
        {
            "question": "What item evolves Clamperl?",
            "answer": "Deep Sea Tooth",
            "correct_emoji": "🦪",
        },
        {
            "question": "How many evolutions does Eevee have?",
            "answer": "8",
            "correct_emoji": "8️⃣",
        },
    ],
    "hardmode": [
        {
            "question": "What is the internal name for MissingNo?",
            "answer": "M00",
            "correct_emoji": "❓",
        },
        {
            "question": "What move does Unown spell in Crystal for Burned Tower?",
            "answer": "EL",
            "correct_emoji": "🔥",
        },
        {
            "question": "What percentage chance to encounter Ditto in Cerulean Cave?",
            "answer": "10%",
            "correct_emoji": "🔟",
        },
        {
            "question": "How many real-world minutes for day/night cycle in Yellow?",
            "answer": "60 minutes",
            "correct_emoji": "⏰",
        },
        {
            "question": "What is the base happiness of Pokemon caught in Heavy Ball?",
            "answer": "0",
            "correct_emoji": "0️⃣",
        },
        {
            "question": "What friendship value needed to evolve Chansey?",
            "answer": "120",
            "correct_emoji": "1️⃣2️⃣0️⃣",
        },
        {
            "question": "How many TMs are there in Generation I?",
            "answer": "50",
            "correct_emoji": "5️⃣0️⃣",
        },
        {
            "question": "What is the catch rate of Mew?",
            "answer": "3",
            "correct_emoji": "3️⃣",
        },
        {
            "question": "What Pokemon has base stat total of 195?",
            "answer": "Delibird",
            "correct_emoji": "🎁",
        },
        {
            "question": "What trainer class uses Chansey in Red/Blue?",
            "answer": "Nurse",
            "correct_emoji": "👩‍⚕️",
        },
    ],
}


def get_questions_for_category(category_id, count=10):
    questions = QUESTIONS.get(category_id, QUESTIONS["general"])
    shuffled = shuffle_array(questions)
    selected = shuffled[: min(count, len(shuffled))]
    return [
        {**q, "options": generate_options(q["answer"], ALL_POKEMON)} for q in selected
    ]


def get_random_questions(count=10):
    all_q = []
    for q_list in QUESTIONS.values():
        all_q.extend(q_list)
    shuffled = shuffle_array(all_q)
    selected = shuffled[: min(count, len(shuffled))]
    return [
        {**q, "options": generate_options(q["answer"], ALL_POKEMON)} for q in selected
    ]


def get_question_count(category_id=None):
    if category_id and category_id in QUESTIONS:
        return len(QUESTIONS[category_id])
    return sum(len(q) for q in QUESTIONS.values())
